apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-kuberenetes
  namespace: jenkins
  labels:
    app: httpd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: 
        ports:
        - containerPort: 80
