apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  selector:
    app: httpd
  type: Nordport
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
      nodeport: 3000
